-- Auto-generated by Matugen
-- VSCode/Catppuccin-inspired color scheme with matugen integration

-- Catppuccin-inspired fixed colors for better syntax highlighting
local catppuccin = {
  red = '#E88594',
  green = '#A3D393',
  yellow = '#E9CE9D',
  blue = '#81C2E1',
  magenta = '#C3A0F3',
  comment = '#6c6c6c',
}

-- Base16 colors setup (VSCode-compatible, no plugin dependency)
local base16 = {
  base00 = '#111318',           -- Background
  base01 = '#1a1b20',  -- Lighter background (status bars, line number)
  base02 = '#282a2f', -- Selection background
  base03 = '#8e9099',           -- Comments, invisibles, line highlighting
  base04 = '#c4c6d0', -- Dark foreground (status bars)
  base05 = '#e2e2e9',        -- Default foreground
  base06 = '#e2e2e9',        -- Light foreground
  base07 = '#37393e',    -- Light background
  base08 = catppuccin.red,                              -- Variables, XML tags, markup link text
  base09 = catppuccin.yellow,                           -- Integers, booleans, constants
  base0A = catppuccin.yellow,                           -- Classes, markup bold
  base0B = catppuccin.green,                            -- Strings, markup code
  base0C = catppuccin.blue,                             -- Support, regular expressions
  base0D = '#bfc6dc',         -- Functions, methods (matugen)
  base0E = '#adc6ff',           -- Keywords, storage (matugen)
  base0F = catppuccin.magenta,                          -- Deprecated, embedded
}

-- Apply base16 colors directly (works in VSCode Neovim)
vim.api.nvim_set_hl(0, 'Normal', { fg = base16.base05, bg = base16.base00 })
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = base16.base05, bg = base16.base01 })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = base16.base05, bg = base16.base00 })


-- Additional highlight customizations for better readability

-- Helper function to set multiple highlight groups at once
local function set_hl_multiple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- UI Elements
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#2b4678',
  fg = nil,
})

vim.api.nvim_set_hl(0, 'CursorLine', {
  bg = '#282a2f',
})

vim.api.nvim_set_hl(0, 'LineNr', {
  fg = '#8e9099',
})

vim.api.nvim_set_hl(0, 'CursorLineNr', {
  fg = '#adc6ff',
  bold = true,
})

-- Comments (italic and muted)
set_hl_multiple({ 'Comment', '@comment' }, {
  fg = catppuccin.comment,
  italic = true,
})

-- Keywords (primary matugen color)
set_hl_multiple({ 'Keyword', '@keyword', '@keyword.control', '@keyword.function', 'Conditional', 'Repeat' }, {
  fg = '#adc6ff',
})

-- Functions (secondary matugen color)
set_hl_multiple({ 'Function', '@function', '@function.call', '@method', '@method.call' }, {
  fg = '#bfc6dc',
})

-- Strings (green)
set_hl_multiple({ 'String', '@string', '@string.escape' }, {
  fg = catppuccin.green,
})

-- Numbers & Constants (yellow/orange)
set_hl_multiple({ 'Number', '@number', 'Boolean', '@boolean', 'Constant', '@constant' }, {
  fg = catppuccin.yellow,
})

-- Types & Classes (blue)
set_hl_multiple({ 'Type', '@type', '@type.builtin', 'Structure', 'StorageClass' }, {
  fg = catppuccin.blue,
})

-- Variables (default text color)
set_hl_multiple({ 'Identifier', '@variable', '@parameter' }, {
  fg = '#e2e2e9',
})

-- Special/Magic variables (red)
set_hl_multiple({ '@variable.builtin', 'Special' }, {
  fg = catppuccin.red,
  italic = true,
})

-- Operators
set_hl_multiple({ 'Operator', '@operator' }, {
  fg = '#e2e2e9',
})

-- Punctuation
set_hl_multiple({ 'Delimiter', '@punctuation.delimiter', '@punctuation.bracket' }, {
  fg = '#c4c6d0',
})

-- Tags (HTML/XML)
set_hl_multiple({ 'Tag', '@tag', '@tag.delimiter' }, {
  fg = '#adc6ff',
})

-- Attributes
set_hl_multiple({ '@tag.attribute' }, {
  fg = '#bfc6dc',
  italic = true,
})

-- Errors & Warnings
vim.api.nvim_set_hl(0, 'Error', {
  fg = catppuccin.red,
  bold = true,
})

vim.api.nvim_set_hl(0, 'DiagnosticError', {
  fg = catppuccin.red,
})

vim.api.nvim_set_hl(0, 'DiagnosticWarn', {
  fg = catppuccin.yellow,
})

vim.api.nvim_set_hl(0, 'DiagnosticInfo', {
  fg = catppuccin.blue,
})

vim.api.nvim_set_hl(0, 'DiagnosticHint', {
  fg = '#c4c6d0',
})

-- Statusline & UI
vim.api.nvim_set_hl(0, 'StatusLine', {
  bg = '#1e1f25',
  fg = '#e2e2e9',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#111318',
  fg = '#e2e2e9',
})

-- Pmenu (completion menu)
vim.api.nvim_set_hl(0, 'Pmenu', {
  bg = '#282a2f',
  fg = '#e2e2e9',
})

vim.api.nvim_set_hl(0, 'PmenuSel', {
  bg = '#adc6ff',
  fg = '#102f60',
})

-- Search
vim.api.nvim_set_hl(0, 'Search', {
  bg = '#3f4759',
  fg = '#dbe2f9',
})

vim.api.nvim_set_hl(0, 'IncSearch', {
  bg = '#adc6ff',
  fg = '#102f60',
})
